version: "2.3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./schema/tasks.sql:/docker-entrypoint-initdb.d/database.sql
  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  postgres: